# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-27 13:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GilKvar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
                ('city', models.CharField(max_length=255, verbose_name='Город')),
                ('street', models.CharField(max_length=255, verbose_name='Улица')),
                ('house', models.CharField(max_length=255, verbose_name='Дом')),
                ('housing', models.CharField(blank=True, max_length=255, null=True, verbose_name='Корпус')),
                ('site', models.CharField(blank=True, max_length=255, null=True, verbose_name='Адрес сайта')),
                ('email', models.CharField(blank=True, max_length=255, null=True, verbose_name='Контактный e-mail')),
                ('phone', models.CharField(blank=True, max_length=255, null=True, verbose_name='Контактный тел')),
            ],
        ),
        migrations.CreateModel(
            name='Houses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=255, unique=True, verbose_name='Уникальный идентификатор')),
                ('housing', models.PositiveIntegerField(default=0, verbose_name='Номер корпуса')),
                ('section', models.PositiveIntegerField(default=0, verbose_name='Номер секции')),
                ('floor', models.PositiveIntegerField(default=0, verbose_name='Номер этажа')),
                ('num_on_floor', models.PositiveIntegerField(default=0, verbose_name='Номер на этаже')),
                ('area', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Площадь')),
                ('price', models.PositiveIntegerField(default=0, verbose_name='Цена')),
                ('gilkvarid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='converter.GilKvar')),
            ],
        ),
    ]
