# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-27 13:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('converter', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Houses',
            new_name='Flat',
        ),
    ]
