# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-27 17:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('converter', '0002_auto_20160427_1659'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flat',
            name='gilkvarid',
        ),
        migrations.AddField(
            model_name='flat',
            name='gilkvar',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='converter.GilKvar', verbose_name='ЖК'),
            preserve_default=False,
        ),
    ]
