# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-28 21:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('converter', '0004_auto_20160428_1753'),
    ]

    operations = [
        migrations.AddField(
            model_name='flat',
            name='balcony',
            field=models.CharField(choices=[('Да', 'Да'), ('Нет', 'Нет')], default='Нет', max_length=2, verbose_name='Адрес сайта'),
        ),
    ]
